services:
  - type: web
    name: nova-agentic-ai
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: bash startup.sh
    envVars:
      - key: RENDER
        value: true
      - key: PYTHON_VERSION
        value: 3.9.18
    autoDeploy: true